### ISSUE TITLE
[Compatibility Request]Vanilla furniture expanded and Simple Chains: Lumber

### ISSUE THREAD

**Issue by mk-over** [jptrrs/BurnItForFuel#6]
Hey jptrrs, thanks for the mod. It's indispensable for me now. If I may, I'm here to request compatibility with two mods:

[Vanilla furniture expanded](https://steamcommunity.com/sharedfiles/filedetails/?id=1718190143) and [Simple Chains: Lumber](https://steamcommunity.com/workshop/filedetails/?id=1708709952)

The former adds a stone campfire and the altter has firewood, logs and green lumber that cannot be used as fuel.
Thanks again for the awesome work!

**Comment by jptrrs** [comment]
Hi There, mk-over! Thanks!
I implemented a new way for the player to choose what goes on the fuel list right form the options panel. You might want to try out the latest version: https://github.com/jptrrs/BurnItForFuel/releases/latest
